RedditClone/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users
  resource :session, only: [:create, :new, :destroy]
  resources :subs
  resources :posts
end

RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

RedditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :string
#  moderator_id :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Sub < ApplicationRecord
  validates :title, :moderator_id, presence: true

  belongs_to :moderator
end

RedditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

# figvaperb
# figvaperb

class User < ApplicationRecord
    attr_reader :password

    validates :username, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6 }, allow_nil: true

    before_validation :ensure_session_token

    has_may :subs,
        foreign_key: :moderator_id,
        dependent: :destroy,
        inverse_of: :moderator

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def is_password?(password)
        bcrypt = BCrypt::Password.new(self.password_digest)
        bcrypt.is_password?(password)
    end

    def generate_unique_session_token
        token = SecureRandom::urlsafe_base64
        while User.exists?(session_token: token)
            token = SecureRandom::urlsafe_base64
        end
        token
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end

    def reset_session_token!
        self.session_token = generate_unique_session_token
        self.save!
        self.session_token
    end



end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #chelll
    #chelll

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def ensure_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def ensure_logged_out
        redirect_to users_url if logged_in?
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
    end

    def logged_in?
        !!current_user
    end

end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :ensure_logged_in, only: [:destroy]
    before_action :ensure_logged_out, only: [:new, :create]

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        
        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            @user = User.new
            flash.now[:errors] = ["Invalid Credentials!"]
            render :new
        end
        
    end

    def new
        @user = User.new
        render :new
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :ensure_logged_in, only: [:destroy, :edit, :update, :index, :show]
    before_action :ensure_logged_out, only: [:new, :create]
    before_action :ensure_moderator, only: [:edit, :update]

    def index
        @subs = Sub.all
        render :index
    end

    def create
        @sub = Sub.new(sub_params)

        if @sub.save
            flash[:messages] = ["Successfully created sub!"]
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def new
        @sub = Sub.new
        render :new
    end

    def edit
        @sub = Sub.find(params[:id])
        render :edit
    end

    def show
        @sub = Sub.find(params[:id])
        render :show
    end

    def update
        @sub = Sub.find(params[:id])
        if @sub
            @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = ["Sub does not exist!!"]
            render :edit
        end

    end

    def destroy
        @sub = Sub.find(params[:id])
        if @sub
            @sub.destroy
            redirect_to subs_url
        else
            flash[:errors] = ["Sub does not exist!!"]
            redirect_to subs_url
        end
    end

    def ensure_moderator
        redirect_to subs_url unless self.moderator_id == current_user.id
    end

    private

    def sub_params
        params.require(:sub).permit(:title, :description, :moderator_id)
    end
end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :ensure_logged_in, only: [:destroy, :edit, :update, :index, :show]
    before_action :ensure_logged_out, only: [:new, :create]

    def index
        @users = User.all
        render :index
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            flash[:messages] = ["Successfully signed up!"]
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def new
        @user = User.new
        render :new
    end

    def edit
        @user = User.find(params[:id])
        render :edit
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def update
        @user = User.find(params[:id])
        if @user
            @user.update(user_params)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = ["User does not exist!!"]
            render :edit
        end

    end

    def destroy
        @user = User.find(params[:id])
        if @user
            @user.destroy
            redirect_to new_user_url
        else
            flash[:errors] = ["User does not exist!!"]
            redirect_to users_url
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end



end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
  <%if logged_in?%>
    <form action="<%=session_url%>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>" >
      <input type="submit" value="Log Out">
    </form>
  <% else %>
    <a href="<%=new_session_url%>">Log in!</a>
    <a href="<%=new_user_url%>">Sign Up!!</a>
  <%end%>
  <%if flash[:errors] %>
    <ul>
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>

  <% end %>
  <%if flash[:messages] %>
    <ul>
      <% flash[:messages].each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

    <%= yield %>
  </body>
</html>

RedditClone/app/views/shared/_form.html.erb
<% action == :edit ? button_value = "Update User" : button_value = "Create User" %>
<% action == :edit ? action_url = edit_user_url : action_url = users_url %>
<form action="<%= action_url %>" method="POST">

    <% if action == :edit %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="username">Username:</label>
    <input type="text" name="user[username]" value="<%= user.username %>">

    <label for="password">Password:</label>
    <input type="password" name="user[password]" value="">

    <input type="submit" value="<%= button_value %>">
</form>

RedditClone/app/views/users/edit.html.erb
<h1>Update user!</h1>

<% render 'shared/form', user: @user, action: :edit %>

RedditClone/app/views/users/index.html.erb
<h1>Here are the Users:</h1>

<ul>
    <% @users.each do |user| %>
        <li>
            <%= user.username %>
        </li>
    <% end %>
</ul>

RedditClone/app/views/users/new.html.erb
<h1>Create a new user!</h1>

<%= render 'shared/form', user: @user, action: :new %>

RedditClone/app/views/users/show.html.erb
<h1>This is: <%= @user.username %></h1>

<h2><%= @user.username %></h2>